name: Run Mypy

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  mypy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install pipenv
        run: pip install --upgrade pip pipenv

      - name: Install dependencies with pipenv
        run: pipenv install --dev

      - name: Run Mypy via script
        run: pipenv run ./scripts/run_mypy.sh